name: kids_learning_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # utility
  get: ^4.7.2
  get_storage: ^2.1.1
  intl: ^0.19.0
  cached_network_image: ^3.4.1
  connectivity_plus: ^6.1.4
  device_info_plus: ^11.4.0
  flutter_cache_manager: ^3.4.1
  dio: ^5.8.0+1
  json_serializable: ^6.9.5
  json_annotation: ^4.9.0
  pretty_dio_logger: ^1.4.0

  # UI
  gap: ^3.0.1
  shimmer: ^3.0.0
  lottie: ^3.3.1
  flutter_svg: ^2.1.0
  cupertino_icons: ^1.0.8
  pin_code_fields: ^8.0.1
  smooth_page_indicator: ^1.2.1
  iconsax: ^0.0.8
  dropdown_button2: ^2.3.9
  audioplayers: ^6.4.0
  gif: ^2.3.0
  just_audio: ^0.10.2
  flutter_native_splash: ^2.4.6
  device_preview: ^1.2.0
  tutorial_coach_mark: ^1.3.0
  shared_preferences: ^2.5.3
  flutter_colorpicker: ^1.1.0
  flutter_animate: ^4.5.2
  just_audio_web: ^0.4.15

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/avatars/
    - assets/images/illustrations/
    - assets/images/logos/
    - assets/images/misc/
    - assets/images/tictactoe/
    - assets/images/mascots/
    - assets/images/mascots/owl/
    - assets/images/mascots/elephant/
    - assets/images/mascots/panda/
    - assets/sfx/
    - assets/sfx/alphabet/
    - assets/icons/
    - assets/lottie/misc/
    - assets/svgs/
    - assets/fonts/
    - assets/
    - assets/images/exercises/size/
    - assets/images/exercises/
    - assets/images/exercises/colors/


  fonts:
    - family: BricolageGrotesque
      fonts:  
        - asset: assets/fonts/BricolageGrotesque-Regular.ttf
        - asset: assets/fonts/BricolageGrotesque-Bold.ttf
          weight: 800
        - asset: assets/fonts/BricolageGrotesque-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/BricolageGrotesque-Medium.ttf
          weight: 500
        - asset: assets/fonts/BricolageGrotesque-Light.ttf
          weight: 300

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/illustrations/splash.png
  
  # Customize the Android and iOS settings
  android_12:
    image: assets/images/illustrations/splash.png
    icon_background_color: "#FFFFFF"
  
  # Positioning and size
  fullscreen: true
  image_size: 200
  
  # Animation branding
  branding: assets/images/logos/logo.png
  branding_mode: bottom
  
  # Disable web support if not needed
  web: false
  
  # Set to "center" to center the icon
  android: true
  ios: true
  
  # Maintain the splash screen longer during development
  android_gravity: center
  ios_content_mode: center


