name: kids_learning_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # utility
  get: ^4.7.2
  intl: ^0.20.2
  cached_network_image: ^3.4.1
  connectivity_plus: ^6.1.4
  device_info_plus: ^11.4.0
  flutter_cache_manager: ^3.4.1
  dio: ^5.8.0+1
  json_serializable: ^6.9.5
  json_annotation: ^4.9.0
  pretty_dio_logger: ^1.4.0

  # UI
  gap: ^3.0.1
  shimmer: ^3.0.0
  lottie: ^3.3.1
  flutter_svg: ^2.1.0
  cupertino_icons: ^1.0.8
  pin_code_fields: ^8.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/avatars/
    - assets/images/logos/
    - assets/images/misc/
    - assets/icons/
    - assets/lottie/
    - assets/svgs/
    - assets/fonts/

  fonts:
    - family: BricolageGrotesque
      fonts:
        - asset: assets/fonts/BricolageGrotesque-Regular.ttf
        - asset: assets/fonts/BricolageGrotesque-Bold.ttf
          weight: 800
        - asset: assets/fonts/BricolageGrotesque-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/BricolageGrotesque-Medium.ttf
          weight: 500
        - asset: assets/fonts/BricolageGrotesque-Light.ttf
          weight: 300
        
  
